-- MySQL Script generated by MySQL Workbench
-- qui 26 mai 2022 21:37:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema comes_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Acompanhamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acompanhamento` (
  `idAcompanhamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`idAcompanhamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `idBebida` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`idBebida`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logadouro` VARCHAR(250) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Lanche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lanche` (
  `idLanche` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`idLanche`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `telefone` BIGINT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idEndereco` INT NOT NULL,
  `idAcompanhamento` INT NOT NULL,
  `idBebida` INT NOT NULL,
  `idLanche` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idBebida_idx` (`idBebida` ASC) VISIBLE,
  INDEX `idAcompanhamento_idx` (`idAcompanhamento` ASC) VISIBLE,
  INDEX `idEndereço_idx` (`idEndereco` ASC) VISIBLE,
  INDEX `idLanche_idx` (`idLanche` ASC) VISIBLE,
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idAcompanhamento`
    FOREIGN KEY (`idAcompanhamento`)
    REFERENCES `mydb`.`Acompanhamento` (`idAcompanhamento`),
  CONSTRAINT `idBebida`
    FOREIGN KEY (`idBebida`)
    REFERENCES `mydb`.`Bebida` (`idBebida`),
  CONSTRAINT `idEndereço`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`),
  CONSTRAINT `idLanche`
    FOREIGN KEY (`idLanche`)
    REFERENCES `mydb`.`Lanche` (`idLanche`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
