-- MySQL Script generated by MySQL Workbench
-- Mon May  2 20:03:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `sobrenome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Acompanhamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acompanhamento` (
  `idAcompanhamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `valor` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`idAcompanhamento`),
  INDEX `fk_Acompanhamento_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Acompanhamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `idBebida` INT NOT NULL AUTO_INCREMENT,
  `opcao` VARCHAR(250) NOT NULL,
  `valor` DECIMAL(2,2) NOT NULL,
  `status` TINYINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idBebida`),
  INDEX `fk_Bebida_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Bebida_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `logadouro` VARCHAR(250) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `opcaoPagamento` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Pagamento` (
  `Pedido_idPedido` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Pagamento_idPagamento`),
  INDEX `fk_Pedido_has_Pagamento_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Pagamento_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Pagamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Pagamento_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Endereço` (
  `Pedido_idPedido` INT NOT NULL,
  `Endereço_idEndereço` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Endereço_idEndereço`),
  INDEX `fk_Pedido_has_Endereço_Endereço1_idx` (`Endereço_idEndereço` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Endereço_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Endereço_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Endereço_Endereço1`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `mydb`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lanche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lanche` (
  `idLanche` INT NOT NULL AUTO_INCREMENT,
  `opcao` VARCHAR(250) NOT NULL,
  `valor` DECIMAL(2,2) NOT NULL,
  `status` TINYINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idLanche`),
  INDEX `fk_Lanche_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Lanche_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
