-- MySQL Script generated by MySQL Workbench
-- qua 18 mai 2022 21:02:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema comes_db
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `logadouro` VARCHAR(250) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idusuario` INT NOT NULL,
  ` Endereço_idEndereço` INT NOT NULL,
  `Endereço_idEndereço` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Usuario_idusuario`, ` Endereço_idEndereço`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_idusuario` ASC, ` Endereço_idEndereço` ASC) VISIBLE,
  INDEX `fk_Pedido_Endereço1_idx` (`Endereço_idEndereço` ASC) VISIBLE)
ENGINE = ARCHIVE
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Acompanhamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acompanhamento` (
  `idAcompanhamento` INT NOT NULL AUTO_INCREMENT,
  `opcao` VARCHAR(250) NOT NULL,
  `valor` DECIMAL(2,2) NOT NULL,
  `status` TINYINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idAcompanhamento`),
  INDEX `fk_Acompanhamento_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Acompanhamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `idBebida` INT NOT NULL AUTO_INCREMENT,
  `opcao` VARCHAR(250) NOT NULL,
  `valor` DECIMAL(2,2) NOT NULL,
  `status` TINYINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idBebida`),
  INDEX `fk_Bebida_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Bebida_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Lanche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lanche` (
  `idLanche` INT NOT NULL AUTO_INCREMENT,
  `opcao` VARCHAR(250) NOT NULL,
  `valor` DECIMAL(2,2) NOT NULL,
  `status` TINYINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idLanche`),
  INDEX `fk_Lanche_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Lanche_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `telefone` BIGINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Usuario_idusuario` INT NOT NULL,
  `Pedido_ Endereço_idEndereço` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Usuario_idusuario` ASC, `Pedido_ Endereço_idEndereço` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Usuario_idusuario` , `Pedido_ Endereço_idEndereço`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Usuario_idusuario` , ` Endereço_idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
